version: '3.8'

services:
  web:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    ports:
      - "8080:80"
    links:
      - php-fpm

  php-fpm:
    image: php:8.3-fpm
    volumes:
      - ./src:/var/www/html
